const projects=[
['Shu Uemura Japan','shu-uemura.svg','React • TypeScript • Responsive Design','https://www.shuuemura.jp/','Worked on the frontend implementation and responsive UI for the Japanese beauty brand website.',1],
['YSL Beauty Japan','ysl-beauty.svg','React • TypeScript • Responsive Design','https://www.yslb.jp/','Contributed to frontend development and responsive web implementation for the Japanese luxury beauty brand website.',1],
['Waseda Zemi','waseda-zemi.svg','React • Responsive Design','https://www.wasedazemi.com/','Developed responsive frontend components and maintained website UI consistency.',1],
['Albion Japan','albion.svg','React • TypeScript','https://albion.co.jp/site/albion/c/c10/','Worked on frontend UI implementation for the Albion Japan website.',1],
['Lipple','lipple.svg','Responsive Web Design','https://lipple.co.jp/','Implemented responsive layouts and frontend website updates.',0],
['Mitsui Credit','mitsui-credit.svg','Responsive Design','https://www.mitsui-credit.com/','Supported frontend development and UI enhancements for the financial services website.',0],
['Mr. Motegi','mr-motegi.svg','HTML • CSS • JavaScript','https://www.mr-motegi.jp/','Built and maintained responsive frontend website components.',0],
['Shibuya JUE Academy','shibuya-jue.svg','Responsive Design','https://shibuya.jue.ac.jp/','Developed responsive layouts and frontend UI sections.',0],
['Yoshida Fukushi','yoshida-fukushi.svg','Responsive Design','https://yoshida-fukushi.jp/','Implemented frontend features and responsive UI improvements.',0],
['Yoshida Koumuin Houka','yoshida-koumuin.svg','Responsive Design','https://yoshida-koumuinhouka.jp/','Worked on responsive frontend development and website maintenance.',0],
['Okawa Kagu','okawa-kagu.svg','Responsive Design','https://www.okawa-kagu.net/','Contributed to frontend implementation and website responsiveness.',0],
['The Company PH','company-ph.svg','React • Responsive Design','https://thecompany.ph/','Developed responsive website sections and frontend UI components.',1],
['The Company SG','company-sg.svg','React • Responsive Design','https://thecompany.sg/','Worked on frontend development and responsive design implementation.',1],
['Allied Pallets','allied-pallets.svg','Responsive Design','https://alliedpallets.com/','Implemented frontend UI improvements and responsive layouts.',0]
];
const featured=document.querySelector('#featured'),more=document.querySelector('#more');
function card(p,i,c=false){return `<article class="card ${c?'compact':''}"><a href="${p[3]}" target="_blank" rel="noreferrer"><img src="images/${p[1]}" alt="${p[0]} website preview" loading="lazy"></a><div class="cardbody"><h3>${p[0]}</h3>${!c?`<p>${p[4]}</p>`:''}<div class="stack"><span>${p[2]}</span></div>${!c?`<a href="${p[3]}" target="_blank" rel="noreferrer">Visit Website ↗</a>`:''}</div></article>`}
projects.filter(p=>p[5]).forEach((p,i)=>featured.insertAdjacentHTML('beforeend',card(p,i)));projects.filter(p=>!p[5]).forEach((p,i)=>more.insertAdjacentHTML('beforeend',card(p,i,true)));
const jobs=[['CODY Web Development, Inc.','Frontend Engineer','May 2020 – Present',['Converted websites for Yves Saint Laurent (YSL) and Shu Uemura using Salesforce Marketing Cloud.','Developed, updated, and maintained customized Japanese WordPress websites.','Implemented UI components and API integrations using ReactJS.','Created custom HTML emails for newsletters and invitations using Benchmark.','Designed and tested responsive websites across multiple browsers and devices.']],['IgniteWebs','Freelance WordPress Developer','December 2021 – June 2022',['Developed and maintained customized Japanese WordPress websites.','Improved CSS and JavaScript implementation to enhance website functionality and user experience.']],['Zeroten Philippines, Inc.','Web Developer','July 2019 – March 2020',['Converted multiple website designs into functional WordPress websites.','Maintained and updated customized WordPress websites.','Tested websites across desktop and mobile devices and conducted QA testing.','Created email templates and campaigns using Mailchimp.','Trained and coached new team members.','Ranked No.1 for Conversion Speed Rating and recognized as a top performer.']],['Proweaver Inc.','WordPress Developer','September 2017 – June 2019',['Developed websites using WordPress Elementor.','Maintained and enhanced existing websites.','Redesigned websites to improve user experience and functionality.']]];
jobs.forEach((j,i)=>document.querySelector('#jobs').insertAdjacentHTML('beforeend',`<article class="job"><div class="jobnum">0${i+1}</div><div class="jobbody"><div class="jobhead"><div><h3>${j[0]}</h3><b>${j[1]}</b></div><time>${j[2]}</time></div><ul>${j[3].map(x=>`<li>✓ ${x}</li>`).join('')}</ul></div></article>`));
document.querySelector('#menu').addEventListener('click',()=>document.querySelector('#nav').classList.toggle('open'));document.querySelectorAll('#nav a').forEach(a=>a.addEventListener('click',()=>document.querySelector('#nav').classList.remove('open')));
